#! /bin/sh

### BEGIN INIT INFO
# Provides:          pisync
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the PiSync service
# Description:       Starts and stops the PiSync multi-room audio software
### END INIT INFO

. /lib/lsb/init-functions

# Script name
NAME=pisync

# App name
DESC=PiSync

# PID file path
PIDFILE=/var/run/$NAME.pid

# Run PiSync as user
RUN_AS=pisync

# Path to app 
APP_PATH=/usr/local/bin/pisync

# path to python bin
DAEMON=/usr/bin/python

DAEMON_OPTS=" PiSync.py --role=auto --daemon --pidfile=${PIDFILE}"

set -e

# Check if there is a stale pidfile. Create and ensure permission correct if no file
if [ -e $PIDFILE ]; then
  PID=`cat $PIDFILE`
  if ! kill -0 $PID > /dev/null 2>&1; then
    echo "" > $PIDFILE
  fi
else
  touch $PIDFILE
  chown $RUN_AS $PIDFILE
fi

case "$1" in
  start)
    echo "Starting $DESC"
    start-stop-daemon -d $APP_PATH -c $RUN_AS --start --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
    ;;
  stop)
    echo "Stopping $DESC"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 15
    ;;
  status)
    status_of_proc -p $PIDFILE "$DAEMON" "$NAME"
    ;;
  restart)
    echo "Restarting $DESC"
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0